BlogProject/Controllers/BlogCommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using BlogBL.Services;
using BlogDAL;
using BlogDAL.Models;
using PagedList;
using PagedList.Mvc;


namespace BlogProject.Controllers
{
    public class BlogCommentsController : Controller
    {
        private ICommentService _commentService;

        public BlogCommentsController(ICommentService commentService)
        {
            _commentService = commentService;
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            return View(await _commentService.GetAllAsync());
        }

        public async Task<ActionResult> Details(int id)
        {
            return View(await _commentService.GetByIdAsync(id));
        }

        [Authorize(Roles = "User")]
        // GET: BlogComments/Create
        public ActionResult Create(int articleId)
        {
            ViewBag.articleId = articleId;
            return View();
        }

        // POST: BlogComments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CommentText,Created,ArticleId")] BlogComments comment)
        {
            if (ModelState.IsValid)
            {
                int id = Convert.ToInt32(Request["articleId"]);
                comment.ArticleId = id;
                comment.CommentCreatedTime = DateTime.Now;
                comment.UserName = User.Identity.Name;
                _commentService.CreateAsync(comment);
                return RedirectToAction("Details", "BlogsArticles", new {id = id});
            }

            return View(comment);
        }

        // GET: BlogComments/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            return View(await _commentService.GetByIdAsync(id));
        }

        // POST: BlogComments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, BlogComments comment)
        {
            try
            {
                comment.Id = id;
                await _commentService.UpdateAsync(comment);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: BlogComments/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            return View(await _commentService.GetByIdAsync(id));
        }

        // POST: BlogComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        ///
        public async Task<ActionResult> Delete(int id, BlogComments comment) 
        {
            try
            {
                await _commentService.DeleteAsync(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public PartialViewResult ViewArticleComments(int id, int? page)
        {
            return PartialView(_commentService.GetAllByArticleIdAsync(id).ToList());
        }
    }
}

BlogProject/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using BlogBL.Services;
using BlogDAL.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;


namespace BlogProject.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        [Authorize(Roles ="Admin")]
        public async Task<ActionResult> Index()
        {            
            return View(await _userService.GetAllUsersAsync());
        }

        public ActionResult Details(int id)
        {
            return View(_userService.GetUserByUserId(id));
        }

        public string GetUserNameByUserId(int userId)
        {
            var user = _userService.GetUserByUserId(userId);
            return user.Username.ToString();
        }

        public ActionResult SignInOrLogIn()
        {
            if (User.Identity.IsAuthenticated)
            {
                if (User.IsInRole("Admin"))
                {
                    return Redirect("AdminPage");
                }
                return Redirect("UserPage");
            }
            return View();
        }

        public ActionResult Create() 
        { 
            return View(); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(BlogUser blogUser)
        {
            try
            {
                
                await _userService.CreateUserAsync(blogUser);
                LoginInfo loginInfoNew = new LoginInfo
                {
                    Username = blogUser.Username,
                    Password = blogUser.Password,
                };
                return RedirectToAction("Login", new {loginInfo = loginInfoNew});
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            return View(); 
        }

        [HttpGet]
        public ActionResult Login()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return View();
            }
            return Redirect("UserPage");
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginInfo loginInfo)
        {
            if (!ModelState.IsValid)
            {
                return Redirect("Login");
            }
            
            var userStore = new UserStore<IdentityUser>();
            var manager = new UserManager<IdentityUser>(userStore);
            if(manager.Find(loginInfo.Username, loginInfo.Password) == null)
            {
                return Redirect("Login");
            }
            var user = manager.Find(loginInfo.Username, loginInfo.Password);
            var authenticationManager = HttpContext.GetOwinContext().Authentication;
            var userIdentity = manager.CreateIdentity(user, DefaultAuthenticationTypes.ApplicationCookie);
            authenticationManager.SignIn(new AuthenticationProperties() { }, userIdentity);
            return RedirectToAction("UserPage");            
        }
        
        [Authorize]
        public async Task<ActionResult> UserPage()
        {
            try
            {
                if (User.IsInRole("Admin"))
                {
                    return Redirect("AdminPage");
                }
                var userModel = await _userService.GetUserByUserName(User.Identity.Name);

                ViewBag.Id = userModel.Id;
                ViewBag.Name = User.Identity.Name;
                return View();
            }
            catch
            {
                return View("Login");
            }
        }

        [Authorize(Roles ="Admin")]
        public ActionResult AdminPage()
        {
            return View();
        }

        [HttpGet]
        public ActionResult SignOut()
        {
            var authenticationManager = HttpContext.GetOwinContext().Authentication;
            authenticationManager.SignOut();

            return RedirectToAction("Index","BlogsArticles");
        }

        public async Task<ActionResult> CreateArticle()
        {
            var userModel = await _userService.GetUserByUserName(User.Identity.Name);
            return RedirectToAction("Create", "BlogsArticles", new { id = userModel.Id });
        }

        public async Task<ActionResult> ShowAllUsersArticles()
        {
            var userModel = await _userService.GetUserByUserName(User.Identity.Name);
            return RedirectToAction("ShowAllForOneUser", "BlogsArticles", new { userId = userModel.Id });

        }

        public ActionResult Delete(int id)
        {
            return View(_userService.GetUserByUserId(id));
        }

        // POST: BlogUser/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, BlogUser blogUser)
        {
            try
            {                
                var userStore = new UserStore<IdentityUser>();
                var manager = new UserManager<IdentityUser>(userStore);
                var userToDelete = manager.FindByName(_userService.GetUserByUserId(id).Username);
                await manager.DeleteAsync(userToDelete);
                await _userService.DeleteAsync(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}                          

BlogProject/Views/User/AdminPage.cshtml
<h1 style="text-align:center">Admin Page</h1>

<br />
<div style="display:grid; grid-template-columns: 2fr 1fr;">
    <div style="border-right-style:solid; border-right-color:lightgray; border-right-width:1px; padding-right: 4%;">
        @Html.ActionLink("Users", "Index", "User")<br />
        @Html.ActionLink("Articles", "AdminArticleView", "BlogsArticles")<br />
        @Html.ActionLink("Comments", "Index", "BlogComments")<br />
    </div>

    <div class="form-group center-block text-center">
        <button type="button" onclick="location.href='@Url.Action("SignOut", "User")'" class="btn btn-toolbar" style="margin-left:0;">
            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Sign Out
        </button>
    </div>
</div>

BlogProject/Views/User/Create.cshtml
@model BlogDAL.Models.BlogUser

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>BlogUser</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlogProject/Views/User/Delete.cshtml
@model BlogDAL.Models.BlogUser

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BlogUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BlogProject/Views/User/Details.cshtml
@model BlogDAL.Models.BlogUser

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>BlogUser</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Username)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Username)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BlogProject/Views/User/Index.cshtml
@model IEnumerable<BlogDAL.Models.BlogUser>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Username)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

BlogProject/Views/User/Login.cshtml
@model BlogDAL.Models.LoginInfo

@{
    ViewBag.Title = "Login";
}



@using (Html.BeginForm(FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <h4 style="text-align:center;">Login</h4>
    <hr />
    <div class="form-horizontal" style="margin-left:25%;">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" >
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlogProject/Views/User/SignInOrLogIn.cshtml
<div style="text-align:center; margin-top:5%; margin-bottom:5%;">
    <h4>@Html.ActionLink("Sign In", "Create", "User")</h4>
    <br />
    <p>or</p>
    <br />
    <h4>@Html.ActionLink("Login", "Login", "User")</h4>
    <small class="form-text text-muted">if you already have an account</small>
</div>

BlogProject/Views/User/UserPage.cshtml
@model BlogDAL.Models.BlogUser

@{
}


<h1 style="text-align:center">My profile</h1>
<div class="form-group">
    <input type="hidden" name="UserId" id="UserId" value="@ViewBag.Id" />
</div>
<br />

<div style="display:grid; grid-template-columns: 2fr 1fr;">
    <div style="border-right-style:solid; border-right-color:lightgray; border-right-width:1px; padding-right: 4%;">
        @{
            Html.RenderAction("ShowAllForOneUser", "BlogsArticles", new { userId = ViewBag.Id });
        }
    </div>

    <div class="form-group center-block text-center">
        <button type="button" onclick="location.href='@Url.Action("CreateArticle", "User")'" class="btn btn-primary">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Article
        </button>
        <br /><br />
        <button type="button" onclick="location.href='@Url.Action("SignOut", "User")'" class="btn btn-toolbar" style="margin-left:0;">
            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> Sign Out
        </button>
    </div>
</div>