BlogProject/Controllers/BlogsArticlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BlogDAL;
using BlogDAL.Models;
using BlogDAL.Repositories;
using BlogBL.Services;
using System.Threading.Tasks;
using PagedList;
using PagedList.Mvc;

namespace BlogProject.Controllers
{
    public class BlogsArticlesController : Controller
    {
        private IArticleService _articleService;
        private ITagService _tagService;

        public BlogsArticlesController(IArticleService articleService, ITagService tagService)
        {
            _articleService = articleService;
            _tagService = tagService;
        }

        // GET: BlogsArticles
        public async Task<ActionResult> Index(int? page)
        {
            var articles = await _articleService.GetAllAsync();
            return View(articles.ToList().ToPagedList(page ?? 1, 9));
        }

        [HttpPost]                                                                          
        public async Task<ActionResult> Index(string SearchString, int? page)
        {
            var articles = await _articleService.GetAllAsync();

            string searchParameter = Request["searchParameter"];
            if (!String.IsNullOrEmpty(SearchString))
            {
                if(searchParameter == "title")
                {
                    articles = articles.Where(s => s.Title.Contains(SearchString));
                }
                else
                {
                    articles = _articleService.GetAllByTagName(SearchString);
                }
                
            }
            return View(articles.ToList().ToPagedList(page ?? 1, 3));
        }

        public PartialViewResult ShowAllForOneUser(int userId)
        {
            return PartialView(_articleService.GetAllForOneUserAsync(userId));
        }

        // GET: BlogsArticles/Details/5
        public async Task<ActionResult> Details(int id)
        {
            return View(await _articleService.GetByIdAsync(id));
        }

        // GET: BlogsArticles/Create
        public ActionResult Create(int id)
        {
            ViewBag.Id = id.ToString();
            return View();
        }

        [Authorize(Roles = "User")]
        public ActionResult CreateComment(int id)
        {
            return RedirectToAction("Create", "BlogComments", new {articleId = id});
        }
        // POST: BlogsArticles/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Title,Text,Created,Category,UserId")] BlogsArticle article)
        {
            if (ModelState.IsValid)
            {                
                int id = Convert.ToInt32(Request["UserId"]);
                article.UserId = id;
                article.Created = DateTime.Now;
                string tagsInput = Request["tagsInput"];
                article.tags = _tagService.CreateAsync(tagsInput).Result.ToList();
                await _articleService.CreateAsync(article);
                return RedirectToAction("Index");
            }

            return View(article);
        }

        // GET: BlogsArticles/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            return View(await _articleService.GetByIdAsync(id));
        }

        // POST: BlogsArticles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, BlogsArticle article)
        {
            try
            {
                article.Id = id;
                await _articleService.UpdateAsync(id,article);

                return RedirectToAction("UserPage","User");
            }
            catch
            {
                return View();
            }
        }

        // GET: BlogsArticles/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            return View(await _articleService.GetByIdAsync(id));
        }

        // POST: BlogsArticles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, BlogsArticle article)
        {
            try
            {
                await _articleService.DeleteAsync(id);
                if (User.IsInRole("Admin"))
                {
                    return RedirectToAction("AdminArticleView");
                }
                return RedirectToAction("UserPage", "User");
            }
            catch
            {
                return View();
            }
        }

        public PartialViewResult ViewArticleTags(int id)
        {
            return PartialView(_tagService.GetAllByArticleId(id));
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> AdminArticleView()
        {
            return View(await _articleService.GetAllAsync());
        }

    }
}

BlogProject/Views/BlogsArticles/AdminArticleView.cshtml
@model IEnumerable<BlogDAL.Models.BlogsArticle>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TextPreview)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tags)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TextPreview)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Category)
        </td>
        <td>
            @{
                Html.RenderAction("ViewArticleTags", "BlogsArticles", new { id = item.Id });
            }
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

BlogProject/Views/BlogsArticles/Create.cshtml
@model BlogDAL.Models.BlogsArticle

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>BlogsArticle</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Tags:</label>
        <div class="col-md-10">
            <p>(write tags starting with # without commas)</p>
            <input type="text" name="tagsInput" id="tagsInput" class="form-control" />
        </div>        
    </div>

    <div class="form-group">
        <input type="hidden" name="UserId" id="UserId" value="@ViewBag.Id" />
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back", "UserPage","User")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlogProject/Views/BlogsArticles/Delete.cshtml
@model BlogDAL.Models.BlogsArticle

<h3>Are you sure you want to delete this?</h3>
<div>
    <div>
        <h2 class="media-heading" style="text-decoration:none; color: black;font-weight:bolder;">@Html.DisplayFor(model => model.Title)</h2>
        <small style="color:cornflowerblue;">@Html.DisplayFor(model => model.Category)</small>
        <div>
            <small>
                @{
                    Html.RenderAction("ViewArticleTags", "BlogsArticles", new { id = Model.Id });
                }
            </small>
        </div>
        <hr />
        @Html.DisplayFor(model => model.Text)

        <hr />
        <small style="color:gray;"><i>Created: @Html.DisplayFor(model => model.Created)</i></small><br />
        <small style="color:gray;"><i>Author: @Html.Action("GetUserNameByUserId", "User", new { userId = Model.UserId })</i></small>

    </div><br />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back", "Index")
        </div>
    }
</div>

BlogProject/Views/BlogsArticles/Details.cshtml
@model BlogDAL.Models.BlogsArticle

@{
    Html.DisplayFor(model => model.Title);
}



<div>
    <h2 class="media-heading" style="text-decoration:none; color: black;font-weight:bolder;">@Html.DisplayFor(model => model.Title)</h2>
    <small style="color:cornflowerblue;">@Html.DisplayFor(model => model.Category)</small>
    <div>
        <small>
            @{
                Html.RenderAction("ViewArticleTags", "BlogsArticles", new { id = Model.Id });
            }
        </small>
    </div>
    <hr />
    @Html.DisplayFor(model => model.Text)

    <hr />
    <small style="color:gray;"><i>Created: @Html.DisplayFor(model => model.Created)</i></small><br />
    <small style="color:gray;"><i>Author: @Html.Action("GetUserNameByUserId", "User", new { userId = Model.UserId })</i></small>

</div>
<br />
<div class="article-comments">
    <h3>Comments</h3><br />
    <hr />
    @{
        Html.RenderAction("ViewArticleComments", "BlogComments", new { id = Model.Id });
    }
</div>


<div style="text-align:center;" class="pull-right">
    <button type="button" onclick="location.href='@Url.Action("CreateComment", "BlogsArticles", new { id = Model.Id })'" class="btn btn-info">
        <span class="glyphicon glyphicon-comment" aria-hidden="true"></span> Comment
    </button>
</div>

BlogProject/Views/BlogsArticles/Edit.cshtml
@model BlogDAL.Models.BlogsArticle

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
        </div>
    </div>

    <div style="display:none">
        @Html.EditorFor(model => model.tags)
        @Html.EditorFor(model => model.Created)
        @Html.EditorFor(model => model.UserId)
        @Html.EditorFor(model => model.BlogUser)
        @Html.EditorFor(model => model.blogsComments)
    </div>
    

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back", "UserPage","User")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

BlogProject/Views/BlogsArticles/Index.cshtml
@using PagedList;
@using PagedList.Mvc;
@model IPagedList<BlogDAL.Models.BlogsArticle>
@Styles.Render("~/Content/ArticlesShowStyles.css")
<h1 style="text-align:center">Main</h1>
<br />

<div style="display:grid; grid-template-columns: 2fr 1fr;">

    <div style="border-right-style:solid; border-right-color:lightgray; border-right-width:1px; padding-right: 4%;">
        <div class="center-block">
            @foreach (var item in Model)
            {
                <div class="text-left article-holder" style="background-color:white; width:100%;">
                    <h4 class="media-heading" style="text-decoration:none; color: black;font-weight:bolder;">@Html.ActionLink(item.Title, "Details", new { id = item.Id }) <br /></h4>
                    <small style="color:cornflowerblue;">@Html.DisplayFor(modelItem => item.Category)</small>
                    <div>
                        <small>
                            @{
                                Html.RenderAction("ViewArticleTags", "BlogsArticles", new { id = item.Id });
                            }
                        </small>
                    </div>
                    <p>@Html.DisplayFor(modelItem => item.TextPreview)</p>
                    <small style="color:gray;"><i>Created: @Html.DisplayFor(modelItem => item.Created)</i></small><br />
                    <small style="color:gray;"><i>Author: @Html.Action("GetUserNameByUserId", "User", new { userId = item.UserId })</i></small>
                </div>
                <hr />
            }
        </div>

        @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
    </div>
    
    <div class="article-holder center-block pull-right">
        <form asp-controller="BlogsArticles" asp-action="Index" method="post" style="margin-left:1%;" >
            <div class="form-group row">
                <input type="search" name="SearchString" id="SearchString" class="form-control" />
            </div>
            <div class="form-group row">
                <button type="submit" class="btn btn-primary" value="Search">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Search
                </button>
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                    <label class="btn btn-secondary">
                        <input type="radio" name="searchParameter" id="option1" autocomplete="off" value="title" style="background-color:gray;"> by title
                    </label>
                    <label class="btn btn-secondary">
                        <input type="radio" name="searchParameter" id="option2" autocomplete="off" value="tag"> by tags
                    </label>
                </div>
            </div>
        </form>
    </div>

</div>

BlogProject/Views/BlogsArticles/ShowAllForOneUser.cshtml
@model IEnumerable<BlogDAL.Models.BlogsArticle>

@Styles.Render("~/Content/ArticlesShowStyles.css")

<div class="center-block text-center">
    @foreach (var item in Model)
    {
        <div class="text-left article-holder" style="background-color:white; width: 100%;">
            <h4 class="media-heading" style="text-decoration:none; color: black;font-weight:bolder;">@Html.ActionLink(item.Title, "Details", new { id = item.Id }) <br /></h4>
            <small style="color:cornflowerblue;">@Html.DisplayFor(modelItem => item.Category)</small>
            <div>
                <small>
                    @{
                        Html.RenderAction("ViewArticleTags", "BlogsArticles", new { id = item.Id });
                    }
                </small>
            </div>
            <p>@Html.DisplayFor(modelItem => item.TextPreview)</p>
            <small style="color:gray;"><i>Created: @Html.DisplayFor(modelItem => item.Created)</i></small><br />
            <small style="color:gray;"><i>Author: @Html.Action("GetUserNameByUserId", "User", new { userId = item.UserId })</i></small>
            <br />
            <div style="text-align:center;" class="pull-right">
                <button type="button" onclick="location.href='@Url.Action("Edit", "BlogsArticles", new { id = item.Id })'" class="btn btn-info">
                    <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit
                </button>
                <button type="button" onclick="location.href='@Url.Action("Delete", "BlogsArticles", new { id = item.Id })'" class="btn btn-danger">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Delete
                </button><br />
            </div>
            <br />

        </div>

    }
</div>

BlogProject/Views/BlogsArticles/ViewArticleTags.cshtml
@model IEnumerable<BlogDAL.Models.Tag>

@foreach (var item in Model) {
<span>#@Html.DisplayFor(modelItem => item.TagName) </span>
}